### ISSUE TITLE
pytest-approvaltests is not compatible with Approval tests 5.0

### ISSUE THREAD

**Issue by aaltat** [approvals/ApprovalTests.Python#109]
[pytest-approvaltests](https://github.com/approvals/ApprovalTests.Python.PytestPlugin) is not compatible with Approval tests 5.0. When I have this test: 
```
from approvaltests.approvals import verify


def test_simple():
    result = "Hello ApprovalTests"
    verify(result)
 ```
 and when I have also pytest-approvaltests installed. I see this error:
 ```
   File "/Users/user/workspace/robotframework-playwright/.venv/lib/python3.9/site-packages/pytest_approvaltests.py", line 4, in <module>
    from approvaltests.reporters import GenericDiffReporterFactory, PythonNativeReporter
ImportError: cannot import name 'PythonNativeReporter' from 'approvaltests.reporters' (/Users/user/workspace/robotframework-playwright/.venv/lib/python3.9/site-packages/approvaltests/reporters/__init__.py)
```

Reported here because pytest-approvaltests does not have issue tracker open.

**Comment by gesellc** [comment]
Going back to 4.1.0 seems to get me a step forward. Maybe valuable for people wo are just setting things up to play around. Can't say if this breaks other dependencies.

requirements.txt:
pytest-approvaltests
approvaltests==4.1.0

**Comment by aaltat** [comment]
I decided to drop using `pytest-approvaltests` and refactored our test to use only `approvaltests`.

**Comment by gesellc** [comment]
Simplicity, I like it!

**Comment by isidore** [comment]
This should now work with pytest-approvaltests 0.2.4 and the latest version of Approvaltests
